# ######################
# SITE SETTINGS
# ######################
# The name of your blog, used in titles and meta tags.
title: ZLA å°ç«™
# A short description that appears after the main title.
subTitle: ZL Asica çš„ä¸ªäººå°ç«™
# A longer description for SEO and meta tags.
description: ZL Asica çš„ä¸ªäººå°ç«™ï¼Œå‘å¸ƒä¸ªäººæŠ€æœ¯å’Œç”Ÿæ´»å†…å®¹ã€‚èµ°è¿‡è·¯è¿‡éƒ½è¿›æ¥çœ‹çœ‹å“¦ ( à¸‡â¼Ì´Ì€Ï‰â¼Ì´ )à¸‡â¼Â³â‚Œâ‚ƒ ï½ï½ï½ # A longer description for SEO and meta tags.
# Comma-separated keywords for SEO purposes.
keywords: 'blog, æŠ€æœ¯, ZL Asica, ZLA, å«’å¸Œå¡'
author:
  name: ZL Asica # Your name, displayed as the author of the blog.
  link: 'https://zla.pub' # Link to your personal website or blog.
# Language setting: Use BCP 47 tag
# e.g., 'en' for English, 'zh-CN' for Simplified Chinese, 'zh-HK' for Traditional Chinese Hong Kong style
lang: zh-CN
# Your public root url, used for SEO and meta tags.
# !Do not include a ending slash
siteUrl: 'https://zla.pub'

# Path to your avatar image. Can be a relative path from /public or a full URL (e.g., https://).
avatar: /images/avatar.jpg
# Used as the default thumbnail for posts without thumbnails.
background: /images/background.jpg
# Slogan displayed on your homepage, under your avatar.
slogan: æœˆäº®ä¸æŠ±ä½ ï¼Œæ˜Ÿæ˜Ÿä¼šè½åœ¨ä½ æ€€é‡Œâœ¨ğŸŒ™
# Google Analytics tracking ID (e.g., 'G-XXXXXXXXXX').
googleAnalytics:

# ######################
# HTML HEAD SETTINGS
# ######################
# Feel free to add more links in Head for your site for better SEO.
# You could generate the links/icons by using https://realfavicongenerator.net/
# Recommend put your icons in /public/icons folder. And follow the examples below.
# Each item here will be rendered as a link tag in the <head> section of your site.
# <link rel="icon" type="image/png" href="/icons/favicon-96x96.png" sizes="96x96" />
# - rel
#   type(optional)
#   href
#   sizes(optional)
links:
  - rel: icon
    type: image/png
    href: /icons/favicon-96x96.png
    sizes: 96x96
  - rel: icon
    type: image/svg+xml
    href: /icons/favicon.svg
  - rel: apple-touch-icon
    href: /icons/apple-touch-icon.png
    sizes: 180x180

# ######################
# POSTS SETTINGS
# ######################
creativeCommons:
  type: CC BY-SA 4.0 Deed
  link: https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans

# ######################
# HEADER SETTINGS
# ######################
# If you want to join the travellings community, set the following field to true.
# For more information, visit https://www.travellings.cn/en_US/
travellings: true

# ######################
# FOOTER SETTINGS
# ######################
# If you want to have a start year of your blog, set the year here.
startYear: 2017 # Leave empty if you do not want to display a start year.

# ######################
# PAGES SETTINGS
# ######################
# Add your AniList username if you want to display your AniList profile.
# Leave the field empty if you do not want to display your AniList profile.
anilist_username: zlasica # Your AniList username. https://anilist.co/user/username
# Set the desired anime name style you want to use.
# Options: 'romaji', 'english', 'native'
# Fallback to 'romaji' if the specified style is not available.
# Default for `ja` locale is 'native', for other locales is 'english'.
anilist_anime_name_style: english

# ######################
# SOCIAL MEDIA SETTINGS
# ######################
# Add your social media usernames.
# Leave the field empty if you do not want to display a specific platform.
# The order of the social media icons is determined by the order below.
socialMedia:
  github_username: ZL-Asica # Your GitHub username. https://github.com/username
  linkedin_username: elara-liu # Your LinkedIn username. https://www.linkedin.com/in/username
  instagram_id: zl_asica # Your Instagram username.
  orcid_id: 0009-0008-7221-2324 # Your ORCID iD.
  telegram_username: zl_asica # Your Telegram username. https://t.me/username
  bluesky_username: zla.app # Your Bluesky username (without prefix). https://bsky.app/profile/{username}
  youtube_id: ZL-Asica # Your YouTube channel ID. https://www.youtube.com/@username
  zhihu_username: zl-asica # Your Zhihu username. https://www.zhihu.com/people/username
  bilibili_id: 29018759 # Your Bilibili ID. https://space.bilibili.com/username
  email: zl@zla.app # Your email address.
  rss: true # Display the RSS icon.

# ######################
# COMMENTS SETTINGS
# Only one of the following two options should be enabled.
# Priority: Twikoo > Disqus
# ######################
# Your Twikoo environment ID.
twikooEnvId: https://vercel.twikoo.zla.app
# Your Disqus shortname (used for integrating Disqus comments).
# Find this in your Disqus account: yoursite.disqus.com (shortname is the part before .disqus.com).
disqusShortname:

# ######################
# CUSTOM CODE BLOCKS
# ! WARNING: Only modify these if you understand the purpose of custom scripts.
# ######################
# Add custom JavaScript code to be included inside the <head> section of your site. One script per line.
headerJavascript:
  - https://cdn.jsdelivr.net/gh/zl-asica/web-cdn/js/zlasica.js
# Add custom HTML code to be included inside the <footer> section of your site.
slotFooter: |
  <a href="http://beian.miit.gov.cn/" target="_blank" rel="noopener noreferrer" class="text-hover-primary underline-interactive" aria-label="é²ICPå¤‡19057855å·-4 å¤‡æ¡ˆä¿¡æ¯">é²ICPå¤‡19057855å·-4</a> <span> | </span> <a href="https://icp.gov.moe/?keyword=20247775" target="_blank" rel="noopener noreferrer" class="text-hover-primary underline-interactive" aria-label="èŒICPå¤‡20247775å· å¤‡æ¡ˆä¿¡æ¯">èŒICPå¤‡20247775å·</a>
